from __future__ import annotations

from typing import Any

from app.storage.base import StoredObject


class SupabaseStorageError(RuntimeError):
    """Raised when the Supabase Storage adapter fails."""


class SupabaseDocumentStorage:
    """Supabase Storage adapter with an injected client.

    The bucket is configuration, while the object path is always generated by
    DocumentService. The adapter never accepts an arbitrary tenant/user ID from
    the HTTP layer as an authorization decision.
    """

    def __init__(self, client: Any, bucket: str = "documents") -> None:
        if not bucket.strip():
            raise ValueError("storage bucket is required")
        self.client = client
        self.bucket = bucket

    def upload(self, *, path: str, content: bytes, content_type: str) -> StoredObject:
        try:
            result = self.client.storage.from_(self.bucket).upload(
                path,
                content,
                {"content-type": content_type, "upsert": False},
            )
        except Exception as exc:  # SDK exception types vary by installed version.
            raise SupabaseStorageError(str(exc)) from exc
        error = getattr(result, "error", None)
        if error:
            raise SupabaseStorageError(str(error))
        return StoredObject(path=path, content_type=content_type, size_bytes=len(content))

    def download(self, *, path: str) -> bytes:
        try:
            result = self.client.storage.from_(self.bucket).download(path)
        except Exception as exc:
            raise SupabaseStorageError(str(exc)) from exc
        error = getattr(result, "error", None)
        if error:
            raise SupabaseStorageError(str(error))
        data = getattr(result, "data", result)
        if not isinstance(data, (bytes, bytearray)):
            raise SupabaseStorageError("Supabase Storage returned non-binary data")
        return bytes(data)

    def delete(self, *, path: str) -> None:
        try:
            result = self.client.storage.from_(self.bucket).remove([path])
        except Exception as exc:
            raise SupabaseStorageError(str(exc)) from exc
        error = getattr(result, "error", None)
        if error:
            raise SupabaseStorageError(str(error))
